### ISSUE TITLE
moduls/QvCanvas.py (80)

### ISSUE THREAD

**Issue by qVistaHost** [SistemesInformacioTerritorial/Qvista#182]
Nom: IMI prePro
Entorn: DSV
Intranet: True
Usuari: D062735
Sessió: 9ecb95e6-3fee-11e9-a92e-6c4b90418db9
___
AttributeError: 'NoneType' object has no attribute 'esborrarSeleccio'
---
Traceback (most recent call last):

**Comment by CPCIMI** [comment]
Faltaba un if para controlar que self.pare no fuera None
