### ISSUE TITLE
moduls/QvAtributs.py (122)

### ISSUE THREAD

**Issue by qVistaHost** [SistemesInformacioTerritorial/Qvista#198]
Nom: IMI prePro
Entorn: DSV
Intranet: True
Usuari: DE1717
Sessió: 5973125e-458c-11e9-8cda-f8bc12a890f7
___
AttributeError: 'NoneType' object has no attribute 'deleteLater'
---
Traceback (most recent call last):
File "N:\SITEB\APL\PyQgis\qVista\Codi\moduls\QvLlegenda.py", line 412, in nouProjecte
    self.atributs.deleteTabs()

**Comment by CPCIMI** [comment]
Corregido: se borran las tabs que contienen las tablas de datos empezando por el mayor número. Por ejemplo, si hay 3 tabs, se borran en este orden: 2, 1 y 0.
